Models/ProductCategory.cs
namespace BuildingShopCore.Models
{
    public class ProductCategory
    {
        public ProductCategory()
        {
            this.Products=new HashSet<Product>();
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; } = false;
        public ICollection<Product> Products { get; set; }
    }
}

Controllers/ProductCategoryController.cs
using BuildingShopCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Extensions;

namespace BuildingShopCore.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly BuildingShopContext _context;

        public ProductCategoryController(BuildingShopContext context)=>
            _context = context;

        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder == "Name" ? "Name_desc" : "Name";
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";

            if (searchString != null) page = 1;
            else searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var categories = await _context.ProductCategories
                .Where(p => p.IsDeleted == false).ToListAsync();
            if (!String.IsNullOrEmpty(searchString))
            {
                categories = categories
                    .Where(c => c.Name.Contains(searchString)
                    || c.Id.ToString().Contains(searchString)
                    && c.IsDeleted == false).ToList();
            }

            switch (sortOrder)
            {
                case "Name":
                    categories = categories.OrderBy(c => c.Name).ToList();
                    break;
                case "Name_desc":
                    categories = categories.OrderByDescending(c => c.Name).ToList();
                    break;
                case "Id_desc":
                    categories = categories.OrderByDescending(c => c.Id).ToList();
                    break;
                default:
                    categories = categories.OrderBy(c => c.Id).ToList();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(categories.ToPagedList(pageNumber, pageSize));
        }

        //public IActionResult Index() =>
        //    View();

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return BadRequest();
            ProductCategory productCategory = await _context.ProductCategories.FindAsync(id);
            if (productCategory == null) return NotFound();
            return View(productCategory);
        }

        public IActionResult Create() =>
            View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(include:"Id,Name")]ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                await _context.ProductCategories.AddAsync(productCategory);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("Notification",
                    $"Категория товаров №{productCategory.Id.ToString()} успешно создана");
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id==null) return BadRequest();
            ProductCategory productCategory = await _context.ProductCategories.FindAsync(id);
            if (productCategory == null) return NotFound();
            return View(productCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind(include: "Id,Name")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(productCategory).State=EntityState.Modified;
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("Notification", $"Категория товаров №{productCategory.Id} успешно изменена");
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id==null) return BadRequest();
            ProductCategory productCategory = await _context.ProductCategories.FindAsync(id);
            if (productCategory == null) return NotFound();
            return View(productCategory);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ProductCategory productCategory = await _context.ProductCategories.FindAsync(id);
            productCategory.IsDeleted = true;
            _context.Entry(productCategory).State= EntityState.Modified;
            await _context.SaveChangesAsync();
            HttpContext.Session.SetString("Notification", $"Категория товаров №{id.ToString()} успешно удалена");
            return RedirectToAction("Index");   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) _context.Dispose();
            base.Dispose(disposing);
        }

        public async Task<IActionResult> CategoryPartialView(string sortOrder,
            string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder == "Name" ? "Name_desc" : "Name";
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";

            if (searchString != null) page = 1;
            else searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var categories = await _context.ProductCategories
                .Where(p=>p.IsDeleted==false).ToListAsync();
            if (!String.IsNullOrEmpty(searchString))
            {
                categories = categories
                    .Where(c => c.Name.Contains(searchString)
                    || c.Id.ToString().Contains(searchString)
                    && c.IsDeleted == false).ToList();
            }

            switch (sortOrder)
            {
                case "Name":
                    categories = categories.OrderBy(c => c.Name).ToList();
                    break;
                case "Name_desc":
                    categories = categories.OrderByDescending(c => c.Name).ToList();
                    break;
                case "Id_desc":
                    categories = categories.OrderByDescending(c => c.Id).ToList();
                    break;
                default:
                    categories = categories.OrderBy(c => c.Id).ToList();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(("_CategoryPartialView"), categories.ToPagedList(pageNumber, pageSize));
        }
    }
}

Views/ProductCategory/Create.cshtml
@model BuildingShopCore.Models.ProductCategory

@{
    ViewData["Title"] = "Добавление";
}

<h2>Создание категории</h2>

<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label text-md-start">Наименование</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <p>
                <div class="form-group">
                     <input type="submit" value="Добавить" class="my-custom-button" />
                     <a asp-action="Index" class="my-custom-link">Назад</a>
                </div>
            </p>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProductCategory/Delete.cshtml
@model BuildingShopCore.Models.ProductCategory

@{
    ViewData["Title"] = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить эту категорию?</h3>
<div class="row">
    <div class="col-md-10">
    <h4>Категория товаров №@Model.Id</h4>
    <hr />
    <form asp-action="Delete">
        <div class="form-group">
                <label asp-for="Name" class="control-label text-md-start">Наименование</label>
                <label class="form-control">@Model.Name</label>
        </div>
        <p>
            <div class="form-group">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Удалить" class="my-custom-button" />
                    <a asp-action="Index" class="my-custom-link">Назад</a>
            </div>
        </p>
    </form>
    </div>
</div>

Views/ProductCategory/Edit.cshtml
@model BuildingShopCore.Models.ProductCategory

@{
    ViewData["Title"] = "Редактирование";
}

<h2>Редактирование категории</h2>

<h4>№@Model.Id</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label text-md-start">Наименование</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <p>
                <div class="form-group">
                        <input type="submit" value="Сохранить" class="my-custom-button"/>
                        <a class="my-custom-link" asp-action="Index">Назад</a>
                </div>
            </p>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProductCategory/Index.cshtml
@model IPagedList<BuildingShopCore.Models.ProductCategory>
@using BuildingShopCore.Controllers;
@using X.PagedList;
@using X.PagedList.Extensions;
@using X.Web.PagedList

<link href="~/css/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewData["Title"] = "Категории товаров";
}

<div class="loader"></div>

<h2>Категории товаров</h2>

<p>
    <a class="my-custom-link" asp-action="Create">Добавить категорию</a>
    <button class="my-custom-link" onclick="window.print();">Печать</button>
</p>

<form id="NewTableId" asp-action="CategoryPartialView" asp-controller="ProductCategory" method="post">
    <div class="form-group">
        <p>
            Поиск: <input type="text" class="form-control" value="@ViewData["CurrentFilter"]" id="searchInput" name="SearchString" oninput="performSearch()" />
        </p>
    </div>
</form>

 <div id="divCategories">
@*      @Html.PartialAsync("CategoryPartialView",Model)
     @Html.Raw(ViewData["Data"]) *@
 </div> 

 @section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            performSearch();
        });


        function performSearch() {
            var searchString = $('#searchInput').val();
            if (searchString.length > 0) {
                $.ajax({
                    url: '@Url.Action("CategoryPartialView", "ProductCategory")',
                    type: 'POST',
                    data: { searchString: searchString},
                    success: function (data) {
                        $('#divCategories').html(data);
                        $('.loader').fadeOut();
                    }
                });
            }
            else {
                $('#divCategories').load('@Url.Action("CategoryPartialView", "ProductCategory")');
            }
        }
    </script>
}

Views/ProductCategory/_CategoryPartialView.cshtml
@model IPagedList<BuildingShopCore.Models.ProductCategory>
@using X.PagedList;
@using X.PagedList.Extensions;
@using X.Web.PagedList

<div class="navbar-nav-scroll">
    <table class="table table-hover" id="CategoriesTable">
        <thead>
            <tr>
                <th scope="col">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="my-custom-button">Номер</a>
                </th>
                <th scope="col">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="my-custom-button">Наименование</a>
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">
                    @item.Id
                </td>
                <td scope="row">
                    @item.Name
                </td>
                <td scope="row">
                    <div class="btn-group dropstart d-print-none">
                    <button class="my-custom-button table-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        </button>
                        <ul class="dropdown-menu text-center">
                            <li><a asp-action="Edit" asp-route-id="@item.Id" class="my-custom-link d-grid">Редактировать</a></li>
                            <li><a asp-action="Delete" asp-route-id="@item.Id" class="my-custom-link d-grid">Удалить</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        }
    </table>
</div>

<div class="d-print-none">
    Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewData["CurrentSort"], currentFilter = ViewData["CurrentFilter"] }))
</div>